# Copyright (C) 2013 Aveco s.r.o.
#
# This file is part of SMake.
#
# SMake is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# SMake is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with SMake.  If not, see <http://www.gnu.org/licenses/>.

#  Library main resource
package SMakeParser::LibResource;

use SMakeParser::MainResource;

@ISA = qw(SMakeParser::MainResource);

use SBuild::LibTask;
use SBuild::LibInstTask;
use SBuild::TargetResource;

#  Ctor
#
#  Usage: newResource($libname, $private, \%args)
sub newResource {
	my $class = $_[0];
	my $this = SMakeParser::MainResource->newResource($_[1]);
	$this->{private} = $_[2];
	$this->setArguments($_[3]);
	bless $this, $class;
}

sub getLibResource {
    my $this = $_[0];
    my $profile = $_[1];
    return $this->createFileResource($this->getPurename . $profile->getToolChain->getLibExtension);
}

#  Get list of real file resources which are generated by this
#  resource.
#
#  This method is used to implement the "TaskAfter" behaviour. The tail
#  .task gets list of real resources and modifies them.
#
#  Usage: getTargetResources($profile): \@list
sub getTargetResources {
    my $this = $_[0];
    my $profile = $_[1];
    return [$this->getLibResource($profile)];
}

#  Extend resource map
#
#  Usage: extendMap($map, $assembler, $profile, $reporter)
sub extendMap {
	return 1;
}

#  Process the main resource
#
#  Usage: processResource($map, $assembler, $profile, $reporter)
sub processResource {
	my $this = $_[0];
	my $map = $_[1];
	my $assembler = $_[2];
	my $profile = $_[3];
	my $reporter = $_[4];
	
	my $objfiles = $assembler->getObjectFiles;
	
	# -- library linking task
	my $libres = $this->getLibResource($profile);
	my $libtask = SBuild::LibTask->newTask(
						$libres->getFilename, $this, 
						[$libres], $objfiles, [], 
						$this->getArguments);
	$assembler->appendTask("link", $libtask);

	if(! $this->{private}) {
		# -- create installation task
		my $insttask = SBuild::LibInstTask->newTask(
						"inst:" . $this->getFilename,
						$this, 
						$libres->getFilename,
						$libres);
		$assembler->appendRawTask("libinst", $insttask);
	}
	
	# -- library clean task
	$assembler->addClean($libres);
	# -- Watcom specific file
#	$assembler->addClean(SBuild::TargetResource->newResource($this->getPurename . ".lst"));
	
	return $libtask;
} 

return 1;
